services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: portfolio_manager
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: portfolio_manager_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app_network

  app:
    build:
      context: .
    image: portfolio_manager
    environment:
      RAILS_MASTER_KEY: "${RAILS_MASTER_KEY}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DATABASE_URL: "postgresql://portfolio_manager:${DB_PASSWORD}@db:5432/portfolio_manager_production"
    ports:
      - "3001:80"
    depends_on:
      - db
    networks:
      - app_network
    volumes:
      - /home/portfolio-manager/storage:/app/storage

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
